Sprint2/step2
vagon3452/react-burger pull request #3
Opened 2023-03-24 15:56 UTC by vagon3452

все плохо, я просто не понимаю как это должно работать

2023-03-24 16:58 UTC, andryxxa93 requested changes
Здравствуйте! Хорошая работа 👍 
Что понравилось:
- Использовали `useCallback` и `useMemo`
- Использовали функции селекторы
- Хорошо организовали хранилище

Что необходимо исправить:
- Файл App.test.tsx необходимо удалить - он проекту не нужен
- папка `services` должна находиться вне директории `components` - это не компоненты. То же касается директории `common`
- Не стоит позволять юзеру делать заказ с пустым конструктором - иначе будет ошибка запроса
- редьюсер должен быть чистой функции, сейчас при каждом вызове добавления ингредиента результат будет отличаться, даже если стейт и экшен одинаковые - будет генерироваться каждый раз новый id,  при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене, а не генерировать в редьюсере. Иначе это делает редьюсер не чистой функцией, что нарушает правило редьюсеров
- Вынесите проверку успешности запроса в отдельную функцию, чтобы не дублировать код. Рекомендую оформить её следующим образом - 
```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

- во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать
- Экшен `POST_ITEMS_FAILED` не отрабатывает при ошибке запроса. Дело в том, что 
 в `postItems` необходимо отлавливать ошибку через цепочку `catch` промиса. То же касается и получения ингредиентов.
- распространенной практикой именования файлов и папок в проекте является стиль `kebab-case` - не используются заглавные буквы, а резделение слов в названии производится за счет тире. Это позволяет избежать ошибок, когда в регистро независимых файловых системах проект собирается, а на других нет
- Файл index.js в папке Actions не нужен - его можно удалить.
- поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте
- Не надо создавать два отдельных модальных окна через портал. Достаточно это сделать в одном файле `Modal` и передавать в него как `children` нужная разметку.


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-24 16:58 UTC, andryxxa93 commented on src/components/Main/Ingridients/BurgerIngredients.js
> +          active={current === "three"}
**Можно лучше**
Не стоит использовать числительные - это усложняет восприятие и расширение кода

2023-03-25 14:07 UTC, vagon3452 commented
незнаю куда засунуть эту ошибку, пойманую в catch. в общем сделал все что смог...

2023-03-26 08:05 UTC, andryxxa93 commented
- Проект не собирается, т.к. не совпадает регистр букв в названии файла или папки при импорте

Проверьте, что в системе контроля версий правильный регистр и при необходимости измените https://noteskeeper.ru/heritage/672/

<img width="1440" alt="Снимок экрана 2023-03-26 в 11 01 32" src="https://user-images.githubusercontent.com/60173362/227763156-bdde8c33-f2da-433f-b8d0-edd9c8e5cab3.png">

 <img width="1438" alt="Снимок экрана 2023-03-26 в 11 04 45" src="https://user-images.githubusercontent.com/60173362/227763301-bc8a80ce-9413-46a8-ab7f-5c993f7ad125.png">

2023-03-26 11:02 UTC, merged

2023-03-26 11:13 UTC, vagon3452 commented
rename